name: Build and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"

      - name: Detener proceso anterior
        run: pm2 stop java || true

      - run: git submodule init
      - run: git submodule update
      - run: git submodule update --remote --recursive

      - name: Build application
        run: gradle build

      - name: Ejecutar
        run: pm2 start java --  -jar -Dserver.port=8080 build/libs/appwebRF-0.0.1-SNAPSHOT.jar
        env:
          PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
          PROD_DB_PORT: ${{ secrets.PROD_DB_PORT }}
          PROD_DB_NAME: ${{ secrets.PROD_DB_NAME }}
          PROD_DB_USERNAME: ${{ secrets.PROD_DB_USERNAME }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
